<?php
echo sprintf(
    '<span id="redactions" data-redactions="%s"></span>',
    $this->escapeHtml(json_encode($redactions))
);
echo sprintf(
    '<span id="form-template" data-form-template="%s"></span>',
    $this->escapeHtml(sprintf(
        '<div class="redaction-div">%s%s%s%s</div>',
        $this->formRow($formTemplate->get('redactions[__INDEX__][property_id]')),
        $this->formRow($formTemplate->get('redactions[__INDEX__][pattern]')),
        $this->formRow($formTemplate->get('redactions[__INDEX__][replacement]')),
        sprintf('<button type="button" class="remove-redaction">%s</button>', $this->translate('Remove'))
    ))
);
?>

<div id="redactions-div"></div>
<button type="button" id="add-redaction"><?php echo $this->translate('Add a redaction'); ?></button>

<script>
const formTemplate = $('#form-template').data('formTemplate');
const redactions = $('#redactions').data('redactions');
const redactionsDiv = $('#redactions-div');
const addRedactionButton = $('#add-redaction');
const addRedaction = function(propertyId, pattern, replacement) {
    // Index redactions by random string.
    let randStr = Math.random().toString(36).substr(7);
    let formTemplateObj = $($.parseHTML(formTemplate.replaceAll('__INDEX__', randStr)));
    formTemplateObj.find('.property-id').val(propertyId);
    formTemplateObj.find('.pattern').val(pattern);
    formTemplateObj.find('.replacement').val(replacement);
    redactionsDiv.append(formTemplateObj);
};
$.each(redactions, function(propertyId, propertyRedactions) {
    $.each(propertyRedactions, function(index, propertyRedaction) {
        addRedaction(propertyId, propertyRedaction[0], propertyRedaction[1]);
    });
});
$(document).ready(function() {
    addRedactionButton.on('click', function(e) {
        addRedaction();
    });
    redactionsDiv.on('click', '.remove-redaction', function(e) {
        $(this).closest('.redaction-div').remove();
    });
});
</script>
