<?php
if ($redaction) {
    $this->htmlElement('body')->appendAttribute('class', 'redact-values redaction edit');
} else {
    $this->htmlElement('body')->appendAttribute('class', 'redact-values redaction add');
}
$form->prepare();
?>

<?php if ($redaction): ?>
<?php echo $this->pageTitle($this->translate('Edit redaction'), 1, $this->translate('Redact Values'), $redaction->label()); ?>
<?php else: ?>
<?php echo $this->pageTitle($this->translate('Add redaction'), 1, $this->translate('Redact Values')); ?>
<?php endif; ?>

<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <?php if ($redaction): ?>
    <a href="#" id="delete-button" class="delete button"><?php echo $this->translate('Delete'); ?></a>
    <?php endif; ?>
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/redact-values-redaction', ['action' => 'browse'], true), ['class' => 'button']); ?>
    <input type="submit" value="<?php echo $this->escapeHtml($this->translate('Submit')); ?>">
</div>

<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>

<?php if ($redaction): ?>
<?php echo $this->deleteConfirm($redaction, $this->translate('redaction')); ?>
<?php endif; ?>

<script>
$(document).ready(function() {
    const resourceTypeSelect = $('#redact-values-resource-type');
    // Prepare the query element when resource type is changed.
    resourceTypeSelect.on('change', function(e) {
        $('.query-form-element').data('resourceType', resourceTypeSelect.val());
        Omeka.closeSidebar($('#query-sidebar-edit'));
        Omeka.closeSidebar($('#query-sidebar-preview'));
    });
});
</script>
